#AUTHENTIFICATE
"/admin/login":
  controller: Authentication
  action: viewAdminLoginForm

"/admin/logAdmin":
  controller: Authentication
  action: authenticateAdmin

"/login":
  controller: Authentication
  action: viewUserLoginForm

"/logUser":
  controller: Authentication
  action: authenticateUser

"/logout":
  controller: Authentication
  action: userLogout

#MENU
"/admin/menu":
  controller: Menu
  action: default

#POST
"/post":
  controller: Post
  action: showOnePost

"/admin/posts":
  controller: Post
  action: showAll

"/admin/createPost":
  controller: Post
  action: createPost

"/admin/savePost":
  controller: Post
  action: savePost

"/admin/deletePost":
  controller: Post
  action: deletePost

"/admin/publishPost":
  controller: Post
  action: publishPost

"/admin/updatePost":
  controller: Post
  action: getUpdateFormView

"/admin/saveUpdatePost":
  controller: Post
  action: updatePost

"/admin/listPosts":
  controller: Post
  action: getAllPostsByStatus

"/admin/changePostStatus":
  controller: Post
  action: changeStatus

#PAGES
"/":
  controller: Page
  action: showFrontPage

"/admin":
  controller: Page
  action: showHomeBack

"/admin/pages":
  controller: Page
  action: showAll

"/admin/createPage":
  controller: Page
  action: createPage

"/admin/savePage":
  controller: Page
  action: savePage

"/admin/updatePage":
  controller: Page
  action: getUpdateFormView

"/admin/saveUpdatePage":
  controller: Page
  action: updatePage

"/admin/deletePage":
  controller: Page
  action: deletePage

"/admin/listPages":
  controller: Page
  action: getAllPagesByStatus

"/admin/changePageStatus":
  controller: Page
  action: changeStatus

"/admin/changePageMenuPosition":
  controller: Page
  action: changeMenuPosition

#COMMENTS
"/admin/approveComment":
  controller: Comment
  action: approveComment

"/admin/rejectComment":
  controller: Comment
  action: rejectComment

"/addComment":
  controller: Comment
  action: saveComment

"/admin/listComments":
  controller: Comment
  action: listCommentsByStatus

#TESTIMONIALS
"/admin/approveTestimonial":
  controller: Testimonial
  action: approveTestimonial

"/admin/rejectTestimonial":
  controller: Testimonial
  action: rejectTestimonial

"/addTestimonial":
  controller: Testimonial
  action: saveTestimonial

"/admin/listTestimonials":
  controller: Testimonial
  action: listTestimonialsByStatus

#USER
"/createUser":
  controller: User
  action: showRegisterForm

"/forgottenPassword":
  controller: User
  action: showForgottenPasswordForm

"/resetPassword":
  controller: User
  action: showResetPasswordForm

"/updatePassword":
  controller: User
  action: resetPwd

"/changePassword":
  controller: User
  action: changePwd

"/mailSended":
  controller: User
  action: sendMailToResetPassword

"/admin/settings":
  controller: User
  action: showUpdateForm

"/saveUser":
  controller: User
  action: saveUser

"/updateUser":
  controller: User
  action: changeUserInfo

"/deleteUser":
  controller: User
  action: deleteUser

"/admin/listUsers":
  controller: User
  action: getAllUsersByProfile

"/admin/changeUserProfile":
  controller: User
  action: changeProfile

#MEDIA
"/admin/addMedia":
  controller: Media
  action: addMedia

#Category
"/admin/listCategory":
  controller: Category
  action: getAllCategory

"/admin/saveCategory":
  controller: Category
  action: saveCategory

#STATIC
"/validation":
  controller: Static
  action: showValidationView
